"""Cross-language test vector validation.

Validates the Python SDK against the reference test vectors in testdata/vectors.json.
These vectors were generated by the Go implementation using deterministic Ed25519 keys.

If these tests pass, the Python implementation is byte-compatible with Go.
"""

import pact
import json
import os
from pathlib import Path

import pytest

# Add parent to path for imports
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))


# Load test vectors
VECTORS_PATH = Path(__file__).parent.parent.parent.parent / \
    "testdata" / "vectors.json"


@pytest.fixture(scope="module")
def vectors():
    with open(VECTORS_PATH) as f:
        return json.load(f)


class TestSeedDerivation:
    """Test that seed derivation matches Go implementation."""

    def test_alice_seed(self, vectors):
        seed = pact.test_vector_seed("alice")
        expected = vectors["seed_derivation"]["alice"]["seed_hex"]
        assert seed.hex() == expected

    def test_bob_agent_seed(self, vectors):
        seed = pact.test_vector_seed("bob-agent")
        expected = vectors["seed_derivation"]["bob_agent"]["seed_hex"]
        assert seed.hex() == expected

    def test_deploy_bot_seed(self, vectors):
        seed = pact.test_vector_seed("deploy-bot")
        expected = vectors["seed_derivation"]["deploy_bot"]["seed_hex"]
        assert seed.hex() == expected


class TestIdentityDerivation:
    """Test that identity IDs match Go implementation."""

    def test_alice_identity(self, vectors):
        seed = pact.test_vector_seed("alice")
        identity = pact.identity_from_seed(seed, "human", "Alice")
        expected = vectors["seed_derivation"]["alice"]

        assert identity.id == expected["identity_id"]
        assert identity.public_key == expected["public_key"]

    def test_bob_agent_identity(self, vectors):
        seed = pact.test_vector_seed("bob-agent")
        identity = pact.identity_from_seed(seed, "agent", "Bob's Agent")
        expected = vectors["seed_derivation"]["bob_agent"]

        assert identity.id == expected["identity_id"]
        assert identity.public_key == expected["public_key"]

    def test_deploy_bot_identity(self, vectors):
        seed = pact.test_vector_seed("deploy-bot")
        identity = pact.identity_from_seed(seed, "agent", "Deploy Bot")
        expected = vectors["seed_derivation"]["deploy_bot"]

        assert identity.id == expected["identity_id"]
        assert identity.public_key == expected["public_key"]


class TestCanonicalJSON:
    """Test that canonical JSON output matches Go implementation."""

    def test_sorted_keys(self, vectors):
        test = vectors["canonical_json"][0]
        result = pact.canonical_json(test["input"])
        assert result.decode("utf-8") == test["output"]

    def test_nested_objects(self, vectors):
        test = vectors["canonical_json"][1]
        result = pact.canonical_json(test["input"])
        assert result.decode("utf-8") == test["output"]


class TestCapabilityNarrowing:
    """Test that capability matching matches Go implementation."""

    def test_all_narrowing_vectors(self, vectors):
        for case in vectors["capability_narrowing"]:
            parent = pact.parse_capability(case["parent"])
            child = pact.parse_capability(case["child"])
            result = parent.covers(child)
            assert result == case["covers"], (
                f"parent={case['parent']}, child={case['child']}: "
                f"expected covers={case['covers']}, got {result}"
            )


class TestContentDigest:
    """Test that content digest matches Go implementation."""

    def test_all_digest_vectors(self, vectors):
        for case in vectors["content_digest"]:
            body = case["body"].encode("utf-8")
            digest = pact.compute_content_digest(body)
            assert digest == case["digest"], (
                f"body={case['body']!r}: expected {case['digest']}, got {digest}"
            )


class TestDelegationSigning:
    """Test that delegation signatures match Go implementation."""

    def test_canonical_payload(self, vectors):
        """Verify the canonical JSON payload matches byte-for-byte."""
        deleg_data = vectors["delegation"]

        # Create Alice and Bob with deterministic seeds
        alice = pact.identity_from_seed(
            pact.test_vector_seed("alice"), "human", "Alice")
        bob = pact.identity_from_seed(pact.test_vector_seed(
            "bob-agent"), "agent", "Bob's Agent")

        # Build a delegation manually (matching test vector fields exactly)
        d = pact.Delegation(
            type="delegation",
            version="1.0",
            id="d-testvector-0001",
            from_entity=pact.DelegationEntity(
                type="human",
                id=alice.id,
                public_key=alice.public_key,
                name="Alice",
            ),
            to_entity=pact.DelegationEntity(
                type="agent",
                id=bob.id,
                public_key=bob.public_key,
                name="Bob's Agent",
            ),
            capabilities=["repo:read,repo=myorg/*",
                          "deploy:create,env=staging"],
            constraints=pact.DelegationConstraints(
                expires="2099-01-01T00:00:00Z",
                max_chain_depth=2,
                not_before="2025-01-01T00:00:00Z",
            ),
            issued_at="2025-01-01T00:00:00Z",
            signature="",
        )

        # Get the canonical payload
        payload = d.signing_payload()
        payload_str = payload.decode("utf-8")

        assert payload_str == deleg_data["canonical_payload"], (
            f"Canonical payload mismatch.\n"
            f"Expected: {deleg_data['canonical_payload']}\n"
            f"Got:      {payload_str}"
        )

    def test_canonical_payload_hex(self, vectors):
        """Verify the hex encoding of the canonical payload."""
        deleg_data = vectors["delegation"]

        alice = pact.identity_from_seed(
            pact.test_vector_seed("alice"), "human", "Alice")
        bob = pact.identity_from_seed(pact.test_vector_seed(
            "bob-agent"), "agent", "Bob's Agent")

        d = pact.Delegation(
            type="delegation",
            version="1.0",
            id="d-testvector-0001",
            from_entity=pact.DelegationEntity(
                type="human",
                id=alice.id,
                public_key=alice.public_key,
                name="Alice",
            ),
            to_entity=pact.DelegationEntity(
                type="agent",
                id=bob.id,
                public_key=bob.public_key,
                name="Bob's Agent",
            ),
            capabilities=["repo:read,repo=myorg/*",
                          "deploy:create,env=staging"],
            constraints=pact.DelegationConstraints(
                expires="2099-01-01T00:00:00Z",
                max_chain_depth=2,
                not_before="2025-01-01T00:00:00Z",
            ),
            issued_at="2025-01-01T00:00:00Z",
            signature="",
        )

        payload = d.signing_payload()
        payload_hex = payload.hex()

        assert payload_hex == deleg_data["canonical_payload_hex"]

    def test_delegation_signature(self, vectors):
        """Verify the Ed25519 signature matches Go implementation."""
        deleg_data = vectors["delegation"]
        signed = deleg_data["signed_delegation"]

        alice = pact.identity_from_seed(
            pact.test_vector_seed("alice"), "human", "Alice")
        bob = pact.identity_from_seed(pact.test_vector_seed(
            "bob-agent"), "agent", "Bob's Agent")

        d = pact.Delegation(
            type="delegation",
            version="1.0",
            id="d-testvector-0001",
            from_entity=pact.DelegationEntity(
                type="human",
                id=alice.id,
                public_key=alice.public_key,
                name="Alice",
            ),
            to_entity=pact.DelegationEntity(
                type="agent",
                id=bob.id,
                public_key=bob.public_key,
                name="Bob's Agent",
            ),
            capabilities=["repo:read,repo=myorg/*",
                          "deploy:create,env=staging"],
            constraints=pact.DelegationConstraints(
                expires="2099-01-01T00:00:00Z",
                max_chain_depth=2,
                not_before="2025-01-01T00:00:00Z",
            ),
            issued_at="2025-01-01T00:00:00Z",
            signature="",
        )

        # Sign with Alice's key
        d._sign(alice)

        assert d.signature == signed["signature"], (
            f"Signature mismatch.\n"
            f"Expected: {signed['signature']}\n"
            f"Got:      {d.signature}"
        )

    def test_signed_delegation_verifies(self, vectors):
        """Verify the Go-generated signature can be verified by Python."""
        signed = vectors["delegation"]["signed_delegation"]

        # Reconstruct alice's public key
        alice = pact.identity_from_seed(
            pact.test_vector_seed("alice"), "human", "Alice")

        # Build delegation from the signed test vector
        d = pact.Delegation.from_dict(signed)

        # Verify: set signature to "", canonicalize, verify with alice's pub key
        payload = d.signing_payload()
        sig_bytes = pact.decode_base64url(signed["signature"])

        assert alice.verify(payload, sig_bytes)
